---
name: ItemIDSearch
main: xtakumatutix\itemids\Main
version: 1.0.0
api: 4.0.0
commands:
  ids:
    description: 手に持っているアイテムIDを表示します。
    usage: /ids
    permission: "ids.command"

permissions:
  ids.command:
    default: op
...
